version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: restaurante-postgres
    environment:
      POSTGRES_DB: sabore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: leonardo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - restaurante-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: leonardorennerdev/restaurante-backend:latest
    container_name: restaurante-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sabore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: leonardo
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - restaurante-network

volumes:
  postgres_data:

networks:
  restaurante-network:
    driver: bridge

